apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-js-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-vika-app
  template:
    metadata:
      labels:
        app: kube-vika-app
    spec:
      containers:
      - name: kube-js-app
        image: bevi13/nginx-alp-js:1.0
        ports:
        - containerPort: 8080
          protocol: TCP
