apiVersion: v1
kind: Service
metadata:
  name: alpinex-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: nginx-alpine
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 32001

